# Prepositions
prepositions = {
    'aboard': 'Preposition',
    'about': 'Preposition',
    'above': 'Preposition',
    'across': 'Preposition',
    'after': 'Preposition',
    'against': 'Preposition',
    'along': 'Preposition',
    'amid': 'Preposition',
    'among': 'Preposition',
    'around': 'Preposition',
    'as': 'Preposition',
    'at': 'Preposition',
    'before': 'Preposition',
    'behind': 'Preposition',
    'below': 'Preposition',
    'beneath': 'Preposition',
    'beside': 'Preposition',
    'between': 'Preposition',
    'beyond': 'Preposition',
    'but': 'Preposition',
    'by': 'Preposition',
    'concerning': 'Preposition',
    'considering': 'Preposition',
    'despite': 'Preposition',
    'down': 'Preposition',
    'during': 'Preposition',
    'except': 'Preposition',
    'for': 'Preposition',
    'from': 'Preposition',
    'in': 'Preposition',
    'inside': 'Preposition',
    'into': 'Preposition',
    'like': 'Preposition',
    'near': 'Preposition',
    'of': 'Preposition',
    'off': 'Preposition',
    'on': 'Preposition',
    'onto': 'Preposition',
    'out': 'Preposition',
    'outside': 'Preposition',
    'over': 'Preposition',
    'past': 'Preposition',
    'regarding': 'Preposition',
    'round': 'Preposition',
    'since': 'Preposition',
    'through': 'Preposition',
    'throughout': 'Preposition',
    'to': 'Preposition',
    'toward': 'Preposition',
    'under': 'Preposition',
    'underneath': 'Preposition',
    'until': 'Preposition',
    'unto': 'Preposition',
    'up': 'Preposition',
    'upon': 'Preposition',
    'with': 'Preposition',
    'within': 'Preposition',
    'without': 'Preposition'
}

# POS tags
pos_tags = {
    'ADJ': 'adjective',
    'ADP': 'adposition',
    'ADV': 'adverb',
    'AUX': 'auxiliary',
    'CCONJ': 'coordinating conjunction',
    'DET': 'determiner',
    'INTJ': 'interjection',
    'NOUN': 'noun',
    'NUM': 'numeral',
    'PART': 'particle',
    'PRON': 'pronoun',
    'PROPN': 'proper noun',
    'PUNCT': 'punctuation',
    'SCONJ': 'subordinating conjunction',
    'SYM': 'symbol',
    'VERB': 'verb',
    'X': 'other'
}
